# local test:  hugo server --config config.toml --bind 127.0.0.1 --port 1313 --baseURL http://localhost:1313/alc-site/ --appendPort=false
baseURL = '/alc-site/'
languageCode = 'zh-cn'
title = 'ALC Beijing'
theme = 'alc-beijing'

# 菜单配置
[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/post/"
    weight = 2
  [[menu.main]]
    identifier = "events"
    name = "活动"
    url = "/event/"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5

# 分页配置
[pagination]
  pagerSize = 9

# 分类和标签配置
[taxonomies]
  category = "categories"
  tag = "tags"

# 参数配置
[params]
  description = "Apache Local Community Beijing - 开源社区"
  author = "ALC Beijing"
  logo = "images/alc-beijing-logo.png"

  # 标签页面分页
  paginateTaxonomy = true
  tagPageSize = 30

  # 社交媒体链接
  social = [
    { name = "github", url = "https://github.com/alc-beijing" },
    { name = "twitter", url = "https://twitter.com/alcbeijing" },
    { name = "wechat", url = "#" }
  ]

  # 快速链接
  quickLinks = [
    { name = "Apache官网", url = "https://apache.org" },
    { name = "Apache Way", url = "https://www.apache.org/theapacheway/" },
    { name = "贡献指南", url = "/alc-site/contributing/" }
  ]

# 忽略日志警告
ignoreLogs = ['warning-goldmark-raw-html']

# 静态资源指纹配置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# 启用资源指纹
enableGitInfo = true
