# local test:  hugo server --config config.toml --bind 127.0.0.1 --port 1313 --baseURL http://localhost:1313/alc-site/ --appendPort=false
baseURL = '/alc-site/'
languageCode = 'zh-cn'
title = 'ALC Beijing'
theme = 'alc-beijing'

# 菜单配置
[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/post/"
    weight = 2
  [[menu.main]]
    identifier = "events"
    name = "活动"
    url = "/event/"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5

# 分页配置
[pagination]
  pagerSize = 9

# 分类和标签配置
[taxonomies]
  category = "categories"
  tag = "tags"

# 参数配置
[params]
  description = "Apache Local Community Beijing - 开源社区"
  author = "ALC Beijing"
  logo = "images/alc-beijing-logo.png"

  # 标签页面分页
  paginateTaxonomy = true
  tagPageSize = 30

  # 社交媒体链接
  social = [
    { name = "github", url = "https://github.com/alc-beijing" },
  ]

  # 快速链接
  quickLinks = [
    { name = "Apache官网", url = "https://apache.org" },
    { name = "Apache Way", url = "https://www.apache.org/theapacheway/" },
    { name = "贡献指南", url = "/alc-site/contributing/" }
  ]

  # 外部项目链接
  externalProjects = [
    { name = "BRPC", url = "https://github.com/apache/brpc", description = "工业级 RPC 框架" },
    { name = "Doris", url = "https://github.com/apache/doris", description = "MPP 数据库" },
    { name = "Dubbo", url = "https://github.com/apache/dubbo", description = "分布式服务框架" },
    { name = "IoTDB", url = "https://github.com/apache/iotdb", description = "时序数据库" },
    { name = "BookKeeper", url = "https://github.com/apache/bookkeeper", description = "分布式日志存储系统" },
    { name = "Pulsar", url = "https://github.com/apache/pulsar", description = "分布式消息系统" },
    { name = "ServiceComb", url = "https://github.com/apache/servicecomb-java-chassis", description = "微服务框架" },
    { name = "ShardingSphere", url = "https://github.com/apache/shardingsphere", description = "分布式数据库中间件" },
    { name = "SkyWalking", url = "https://github.com/apache/skywalking", description = "应用性能监控" },
    { name = "RocketMQ", url = "https://github.com/apache/rocketmq", description = "分布式消息队列" }
  ]

  # 联系链接
  contactLinks = [
    { name = "GitHub", url = "https://github.com/alc-beijing", icon = "fab fa-github", description = "关注我们的 GitHub 组织" },
    { name = "翻译项目", url = "https://github.com/alc-beijing/translation", icon = "fas fa-language", description = "帮助翻译文档和内容" }
  ]

# 忽略日志警告
ignoreLogs = ['warning-goldmark-raw-html']

# 静态资源指纹配置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# 启用资源指纹
enableGitInfo = true
